version: '3'
services:
  mysql:
    restart: unless-stopped
    image: mysql:5.6.51
    container_name: mysql-5.6
    volumes:
      - ./mydir:/mydir
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      ##- ./source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=lan123456"
      ##- "MYSQL_DATABASE=yourdbname"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306