version: "3.0"
services:
  memos:
    image: neosmemo/memos:0.11.2
    container_name: memos
    restart: unless-stopped
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      - mode=prod